# Generated by Django 5.0.6 on 2024-06-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_de_tiempo', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('sensor', 'Sensor'), ('reloj', 'Reloj')], default='sensor', max_length=10)),
                ('tiempo', models.TimeField(default='00:00:00')),
                ('formato_tiempo', models.CharField(default='HH:MM:SS', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('sensor', 'Sensor'), ('reloj', 'Reloj')], default='sensor', max_length=10)),
                ('valor', models.FloatField(default=0.0)),
                ('unidad_de_medida', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('sensor', 'Sensor'), ('reloj', 'Reloj')], default='sensor', max_length=10)),
                ('state', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('condicion', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('sensor_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_sensor', to='models.sensor')),
                ('interruptor_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_interruptor', to='models.switch')),
            ],
        ),
    ]
