# Generated by Django 5.0.6 on 2024-06-27 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_reloj_topic_alter_sensor_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regla',
            name='interruptor_asociado',
        ),
        migrations.AddField(
            model_name='regla',
            name='switch_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_switch', to='models.switch'),
        ),
        migrations.AlterField(
            model_name='regla',
            name='sensor_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_sensor', to='models.sensor'),
        ),
    ]
