# Generated by Django 4.2.2 on 2024-04-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='black_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='board_state',
            field=models.TextField(help_text='Almacena la posición de las piezas en formato FEN', verbose_name='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Game ending time', null=True, verbose_name='Ending'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='start_time',
            field=models.DateTimeField(auto_now=True, help_text='Game starting time', null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activa'), ('FINISHED', 'Finalizada')], default='PENDING', max_length=64),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='time_control',
            field=models.CharField(help_text='Control de tiempo para cada jugador', max_length=50, verbose_name='Time Control'),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
