# Generated by Django 4.2.2 on 2024-04-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_chessgame_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='black_player',
            new_name='black',
        ),
        migrations.RenameField(
            model_name='chessgame',
            old_name='white_player',
            new_name='white',
        ),
    ]
