# Generated by Django 4.2.2 on 2024-04-06 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_chessgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
