# Generated by Django 4.2.2 on 2024-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_remove_chessgame_black_remove_chessgame_white_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chessgame',
            old_name='time_control',
            new_name='timeControl',
        ),
    ]
