# Generated by Django 4.2.2 on 2024-04-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_rename_time_control_chessgame_timecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmove',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='models.chessgame'),
        ),
    ]
