# Generated by Django 4.2.2 on 2024-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_chessmove_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='board_state',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='Almacena la posición de las piezas en formato FEN'),
        ),
    ]
