# Generated by Django 5.0.6 on 2024-06-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_reloj_formato_tiempo_remove_reloj_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloj',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('sensor', 'Sensor'), ('reloj', 'Reloj')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('sensor', 'Sensor'), ('reloj', 'Reloj')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='device_type',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('sensor', 'Sensor'), ('reloj', 'Reloj')], default=None, max_length=10, null=True),
        ),
    ]
