EXPLAIN ANALYZE 
SELECT COUNT(*)
FROM public.orders
WHERE STATUS IS NULL;

EXPLAIN ANALYZE 
SELECT COUNT(*)
FROM public.orders
WHERE STATUS = 'Shipped';

CREATE INDEX INDEX_STATUS ON public.orders(STATUS);
--DROP INDEX INDEX_STATUS;

EXPLAIN ANALYZE 
SELECT COUNT(*)
FROM public.orders
WHERE STATUS IS NULL;

EXPLAIN ANALYZE 
SELECT COUNT(*)
FROM public.orders
WHERE STATUS = 'Shipped';

ANALYZE VERBOSE public.orders;

EXPLAIN ANALYZE
SELECT COUNT(*)
FROM public.orders
WHERE STATUS IS NULL;

EXPLAIN ANALYZE
SELECT COUNT(*)
FROM public.orders
WHERE STATUS = 'Shipped';

EXPLAIN ANALYZE
SELECT COUNT(*)
FROM public.orders
WHERE STATUS = 'Paid';

EXPLAIN ANALYZE
SELECT COUNT(*)
FROM public.orders
WHERE STATUS = 'Processed';
