# Generated by Django 5.0.6 on 2024-06-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_reloj_device_type_alter_sensor_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='reloj',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='device_type',
        ),
        migrations.AddField(
            model_name='evento',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_sensor', to='models.sensor'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
